### ISSUE TITLE
fixing errors which occurred due to deprecated version of some widgets and some other syntax errors

### ISSUE THREAD

**Issue by ShubhamTiwari55** [HackSlashNITP/Cura#2]
There are some errors and warnings due to use of deprecated versions of some widgets and in some files there is a widget uniDirectionalBackground() which is causing problem as it is imported from 2 different places. Also the firebase part is not working properly. so kindly look if firebase account is working or not and please allow me to fix the issues @RitwikSingh28

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
The errors due to deprecated widgets and `uniDirectionalBackground()` are already being taken care of in Issue #1 .

If interested, I will assign Issue #1 to you as well, so you can collaborate with the other contributor to make the changes before the deadline, i.e. **5th October, 2023**

**Comment by ShubhamTiwari55** [comment]
Yes sir I'm interested. kindly assign this issue to me as well

**Comment by RitwikSingh28** [comment]
@ShubhamTiwari55 
The issues mentioned here have been fixed in #3.

Closing this issue
